import React from 'react'
import { PRICING_CONFIG } from '../../config/pricing'

const SEOFooter = ({ pageType = 'general', customContent = null }) => {
  // Get common pricing data
  const essentialPrice = PRICING_CONFIG.packages.professional.perEdit
  const deliveryTime = PRICING_CONFIG.delivery.standard.time
  const alacartePrice = PRICING_CONFIG.alacarte.perEdit

  // Define SEO content for different page types
  const seoContent = {
    general: `Sprintix Studio is Singapore's premier photo editing service, specializing in professional product photography enhancement for e-commerce businesses. Our expert team delivers marketplace-ready images optimized for Lazada, Shopee, Amazon, and other major platforms. With ${deliveryTime} standard delivery and transparent bulk pricing starting at SGD ${essentialPrice} per edit, we make professional photo editing accessible to businesses of all sizes. From background removal and color correction to platform-specific resizing and creative graphics, Sprintix helps Southeast Asian sellers boost their conversion rates with stunning product visuals that drive sales and engagement.`,
    
    'background-removal': `Sprintix is Singapore's leading background removal service, specializing in marketplace-ready product photography for Lazada, Shopee, and Amazon sellers. Our expert team combines AI-powered precision with human artistry to deliver pixel-perfect white background photo editing that meets strict e-commerce compliance standards. From complex product cutouts to bulk background removal, we help Southeast Asian businesses transform cluttered product shots into conversion-driving visuals. With ${deliveryTime} turnaround times and transparent bulk pricing starting at SGD ${essentialPrice} per edit in our Essential package, Sprintix makes professional photo editing accessible to solo entrepreneurs and established brands alike. Whether you need Lazada image compliance, Shopee listing optimization, or Amazon product photo enhancement, our background removal service Singapore ensures your products stand out in crowded marketplaces while saving you countless hours of DIY frustration.`,
    
    'photo-editing': `Sprintix Studio offers comprehensive photo editing services tailored for e-commerce success in Singapore and Southeast Asia. Our professional editors specialize in product photography enhancement, including background removal, color correction, lighting adjustment, and platform-specific optimization for Lazada, Shopee, Amazon, and Instagram. With bulk packages starting at SGD ${essentialPrice} per edit and ${deliveryTime} delivery guarantee, we help online sellers create compelling product visuals that increase conversion rates. From basic touch-ups to complex creative graphics and infographics, Sprintix combines technical expertise with commercial understanding to deliver photos that sell. Our Singapore-based team understands local market preferences and international e-commerce standards, ensuring your products look professional across all sales channels.`,
    
    'pricing': `Sprintix Studio offers transparent, competitive pricing for professional photo editing services in Singapore. Our bulk packages provide exceptional value, with our popular Essential package offering 25 edits at SGD ${essentialPrice} per image, including background removal, color correction, and platform optimization. For single edits, our à la carte service is available at SGD ${alacartePrice} per image. All packages include ${deliveryTime} standard delivery, multiple revision rounds, and dedicated support. Whether you're a small business starting with our Starter package or an enterprise requiring our large-volume solution, Sprintix makes professional photo editing affordable and accessible. No hidden fees, no subscription commitments – just transparent pricing that scales with your business needs across Lazada, Shopee, Amazon, and other e-commerce platforms.`,
    
    'about': `Sprintix Studio is Singapore's trusted partner for professional e-commerce photo editing, serving hundreds of businesses across Southeast Asia since our founding. Our experienced team of graphic designers and photo editors specializes in creating marketplace-ready product images that drive conversions on Lazada, Shopee, Amazon, and other major platforms. With state-of-the-art editing facilities and streamlined workflows, we deliver consistent, high-quality results within ${deliveryTime} while maintaining competitive pricing starting at SGD ${essentialPrice} per edit. From solo entrepreneurs launching their first products to established brands managing thousands of SKUs, Sprintix has become the go-to solution for businesses seeking reliable, professional photo editing services that understand the unique requirements of Asian e-commerce markets.`,
    
    'health-beauty': `Sprintix Studio specializes in health and beauty product photography editing for Singapore's thriving e-commerce market. Our expert editors understand the unique requirements of cosmetics, skincare, supplements, and wellness products, delivering stunning visuals optimized for Lazada, Shopee, Amazon, and beauty-focused platforms. With precise color correction to accurately represent product shades, sophisticated background removal for clean presentation, and platform-specific formatting, we help beauty brands showcase their products professionally. Starting at SGD ${essentialPrice} per edit with ${deliveryTime} delivery, our health and beauty photo editing services include ingredient highlight graphics, before-and-after presentations, and compliance-ready images that meet strict marketplace standards while appealing to Singapore and regional beauty consumers.`,
    
    'sports-lifestyle': `Sprintix Studio delivers dynamic sports and lifestyle product photography editing services designed for Singapore's active consumer market. Our specialized editing team creates compelling visuals for fitness equipment, athletic wear, outdoor gear, and lifestyle products that perform exceptionally on Lazada, Shopee, Amazon, and sports retailer platforms. With action-focused editing techniques, lifestyle background integration, and platform-optimized formatting, we help sports brands connect with their target audience. Our sports and lifestyle editing services start at SGD ${essentialPrice} per edit with ${deliveryTime} standard delivery, including dynamic background replacements, product-in-use mockups, and size-specific formatting that showcases your products' performance benefits and lifestyle appeal to Singapore and Southeast Asian fitness enthusiasts.`,
    
    'lazada': `Sprintix Studio is your Lazada specialist for product photo editing and optimization in Singapore and Southeast Asia. We understand Lazada's strict image requirements, quality guidelines, and seller standards, ensuring your products pass all quality checks while maximizing visual appeal. Our Lazada-focused editing services include precise background removal to meet platform standards, optimized image sizing for mobile and desktop viewing, enhanced product visibility through professional lighting and color correction, and promotional graphic creation for Lazada campaigns. With bulk packages starting at SGD ${essentialPrice} per edit and ${deliveryTime} delivery, we help Lazada sellers increase their approval rates, improve search rankings, and boost conversion rates through professionally edited product images that comply with all marketplace requirements while standing out from competitors.`,
    
    'help': `Sprintix Studio provides comprehensive support and professional photo editing services for Singapore e-commerce businesses. Our help center covers everything from order placement and file requirements to delivery timelines and revision processes. With transparent pricing starting at SGD ${essentialPrice} per edit and reliable ${deliveryTime} delivery, we make professional photo editing accessible and straightforward. Whether you need assistance with background removal, color correction, platform optimization, or bulk order management, our Singapore-based support team is ready to help. We serve businesses of all sizes across Lazada, Shopee, Amazon, and other major platforms, providing expert guidance on image requirements, best practices, and optimization strategies that drive sales and improve marketplace performance.`,
    
    'careers': `Join Sprintix Studio, Singapore's leading photo editing service provider, and build your career in the exciting world of e-commerce visual content creation. We're always seeking talented graphic designers, photo editors, and digital marketing professionals who are passionate about helping businesses succeed through compelling product photography. Our team works with cutting-edge editing software and serves clients across Lazada, Shopee, Amazon, and major Southeast Asian marketplaces. With competitive packages and the opportunity to work on diverse projects from beauty and fashion to electronics and lifestyle products, Sprintix offers career growth in Singapore's thriving digital economy. Join us in delivering professional editing services that transform product images and drive e-commerce success across the region.`,
    
    'shopify': `Sprintix Studio is Singapore's premier Shopify optimization specialist, delivering speed-optimized product images and visual enhancements that supercharge e-commerce performance. Our expert team combines technical Shopify expertise with professional photo editing to create lightning-fast, conversion-driving store experiences. From WebP and AVIF image conversion to responsive collection banners and comprehensive speed audits, we help Shopify merchants achieve faster load times, higher conversion rates, and improved search rankings. With our signature Shopify Store Optimizer package at SGD 290, including implementation guides for Dawn 2.0+ themes and SEO-optimized alt-text, Sprintix transforms slow-loading stores into high-converting sales machines. Serving Singapore and Southeast Asian Shopify merchants with ${deliveryTime} delivery and proven results including 65% faster page loads and 47% higher conversion rates. Trust Sprintix to optimize your Shopify store with pixel-perfect visuals that load fast and convert better.`
  }

  // Use custom content if provided, otherwise use predefined content
  const content = customContent || seoContent[pageType] || seoContent.general

  return (
    <section className="sr-only" aria-hidden="true">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <p>{content}</p>
        </div>
      </div>
    </section>
  )
}

export default SEOFooter